<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/style.css">
  <title>Document</title>
</head>
<body>
  <div class="wrapper">
    <header class="header">
     <%@ include file="headerBar.jsp" %>
    </header>
    <main class="main">
      <div class="main__title">Terms & Conditions</div>
      <div class="main__login-container">
        <p class="terms"><span class="first-word">Following</span> are the terms and conditions or "Terms" that govern your use of any website that links to these Terms (the "Site"). By using or visiting the Site, you expressly agree to be bound by these Terms and all applicable laws and regulations governing the Site. ASPENCORE, our parent, and its subsidiaries and/or affiliates (collectively, "we", "us", or "our") reserve the right to change these Terms at any time, effective immediately upon posting or linking on the Site. If you violate these Terms, we may terminate your use of the Site, bar you from future use of the Site, and/or take appropriate legal action against you.</p>
        <p class="terms"><span class="first-word">You agree</span> that you are only authorized to visit and view pages of this Site for your own personal use, and that you shall not duplicate, publish, modify or otherwise distribute the material on this Site for any purpose other than as set forth herein. You may only use the Site as permitted by law, including applicable export and re-export laws and regulations. The software on this Site and any Content posted on the Site are our property and are protected by U.S. and international copyright laws. You agree that you will not remove, obscure or alter any legal notices displayed on the Site.</p>
        <p class="terms"><span class="first-word">You agree</span> that you will not use the Site (i) in connection with or to promote any products, services, or materials; (ii) in any manner or for any purpose that violates any law or regulation, any right of any person, including but not limited to intellectual property rights, rights of privacy, or rights of personality; (iii) to post any information that disparages or defames any person or entity; (iv) to upload or transmit viruses or malicious code; (v) to harass, bully, or intimidate any users; or (vi) to post content that is hateful, threatening, violent, pornographic, defamatory, abusive, deceptive, or otherwise inappropriate.</p>
        <p class="terms"><span class="first-word">By using</span> the Site to search for or link to another site, you agree and understand that you may not make any claim against us for any damages or losses whatsoever resulting from your use of the Site to obtain search results or to link to another site.</p>
        <p class="terms"><span class="first-word">You agree</span> that you will not use any robot, spider, other automatic device, or manual process to monitor or copy our Site or the Content contained thereon, to access or capture data, or for any other unauthorized purpose without our prior express written permission. You agree that you will not use any device, software or routine to interfere or attempt to interfere with the proper working of the Site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure. The Content is protected by copyright laws, international copyright treaties, as well as other laws and conventions related to intellectual property. You agree that you will observe such laws and in particular shall not modify, conceal or remove any alphanumeric code, marks or copyright notices from the Content, the software or documentation, or any copies thereof.</p>
        <p class="terms"><span class="first-word">Certain</span> functionality on this Site may require the use of an account. You are solely responsible for maintaining the security of your ID and password. If you suspect that someone else knows or has changed your password, please reset it so that no one else can sign in to your account. You agree not to (i) provide false information when creating your account; (ii) create an account for others without their permission; (iii) create more than one account; (iv) share your login information with others; (v) attempt to access an account belonging to someone else or to solicit login information from others; or (vi) create another account without our permission if your account has been disabled. In addition, you agree to provide accurate profile and contact information and to keep such information up to date.</p>
        <p class="terms"><span class="first-word">Illegal</span> and/or unauthorized uses of the Site, including, but not limited to unauthorized framing of or linking to the Site, or unauthorized use of any robot, spider or other automated device on the site, will be investigated and appropriate legal action will be taken, including without limitation civil, criminal and injunctive redress. You agree that you will comply with any security processes and procedures (such as passwords) we specify with respect to access to or use of the Site. Further, you agree not to access or attempt to access any areas of or through a Site which are not intended for general public access, unless we have provided you with written authorization to do so.</p>
        <p class="terms"><span class="first-word">You agree</span> that you will only use the Site only for lawful purposes. You will not transmit, post, store, distribute, display or present any information, software, data, file or material in violation of any applicable law or regulation. You will not use the Site to facilitate, or otherwise assist others in, the violation of any law or regulation. You are solely responsible for ensuring that materials transmitted, posted, stored, distributed, displayed or presented using the Site comply with this Agreement and all applicable laws and regulations.</p>
        <p class="terms"><span class="first-word">You</span> understand and agree that in our sole discretion, and without prior notice, we may terminate your access to the Site, or exercise any other remedy available if we believe that your use is (i) inconsistent with these Terms or (ii) has violated our rights, the rights of another user, or the law. You agree that monetary damages may not provide us with a sufficient remedy for violations of these terms and conditions, and you consent to injunctive or other equitable relief for such violations. We may release user information about you if required by law or subpoena, or if the information is necessary or appropriate to release to address an unlawful or harmful activity.</p>
      </div>
    </main>
    <footer class="footer">
    <%@ include file="footerBar.jsp" %>
    </footer>
  </div>
</body>
</html>